import React, { useState } from "react";
import { Plus, RotateCcw, Search } from "lucide-react";
import { SEED_EVIDENCE, fmt, truncate } from "../lib/evidenceMeta";
import { AppHeader, SkillIcon, StatusBadge, TypeBadge } from "./Shared";

const TABS = [
  { key: "all", label: "All" },
  { key: "pending", label: "Pending" },
  { key: "approved", label: "Approved" },
  { key: "rejected", label: "Rejected" },
  { key: "revision", label: "Revision" },
];

export default function EvidenceStatus({ evidence = SEED_EVIDENCE, onAdd = () => {}, onOpen = () => {} }) {
  const [filter, setFilter] = useState("all");
  const [query, setQuery] = useState("");
  const records = Array.isArray(evidence) ? evidence : [];
  const counts = TABS.reduce((acc, tab) => ({ ...acc, [tab.key]: tab.key === "all" ? records.length : records.filter((item) => item.status === tab.key).length }), {});
  const shown = records.filter((item) => (filter === "all" || item.status === filter) && `${item.skill} ${item.type} ${item.description} ${item.url}`.toLowerCase().includes(query.toLowerCase()));

  return <main className="min-h-screen bg-[#f8f8fa] text-[#111827]">
    <AppHeader action={<><span className="hidden text-[10px] text-[#aab4d0] sm:inline">Ahmed Khalil · Learner</span><button type="button" onClick={() => onAdd()} className="inline-flex h-7 items-center gap-1.5 rounded-[5px] bg-[#315cff] px-3 text-[10px] font-semibold text-white shadow-sm transition hover:bg-[#2348c5] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-white/50"><Plus size={12} />Add Evidence</button></>} />
    <div className="mx-auto max-w-[1180px] px-5 pb-12 pt-7 sm:px-8">
      <header className="mb-5 flex items-start justify-between gap-6"><div><h1 className="m-0 text-[20px] font-semibold tracking-[-.025em] text-[#18191f]">Evidence Status</h1><p className="m-0 mt-1 text-[11px] text-[#878b94]">Track review progress for all submitted evidence — AC-09</p></div></header>
      <div className="mb-5 flex flex-wrap items-center gap-1.5 border-b border-[#e7e8eb] pb-2.5" role="tablist" aria-label="Evidence status filters">{TABS.map((tab) => <button key={tab.key} type="button" role="tab" aria-selected={filter === tab.key} onClick={() => setFilter(tab.key)} className={`inline-flex h-6 items-center gap-1 rounded-[4px] px-2.5 text-[9px] transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#2f5bea]/30 ${filter === tab.key ? "border border-[#d7dbe2] bg-white font-semibold text-[#16181d] shadow-[0_1px_2px_rgba(0,0,0,.04)]" : "text-[#8b8f98] hover:bg-white hover:text-[#343740]"}`}>{tab.label}<span className={`min-w-3.5 rounded-[3px] px-1 text-center text-[8px] ${filter === tab.key ? "bg-[#f0f1f3] text-[#626772]" : "text-[#a1a5ad]"}`}>{counts[tab.key]}</span></button>)}<label className="ml-auto flex h-6 w-[160px] items-center gap-1.5 rounded-[4px] border border-[#dedfe3] bg-white px-2 text-[#a4a7ae] focus-within:border-[#2f5bea] sm:w-[190px]"><Search size={11}/><input aria-label="Search evidence" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search evidence" className="w-full bg-transparent text-[9px] text-[#272932] outline-none placeholder:text-[#a4a7ae]"/></label></div>
      <div className="mb-2 flex items-center justify-between"><p className="m-0 text-[10px] font-semibold text-[#4c5059]">Submitted evidence <span className="font-normal text-[#9a9da5]">({shown.length})</span></p><p className="m-0 text-[9px] text-[#a1a4ac]">Last updated today</p></div>
      <div className="space-y-3">{records.length === 0 ? <div className="flex flex-col items-center gap-3 px-5 py-16 text-center"><p className="m-0 text-xs text-[#8b8f98]">No evidence submitted yet.</p><button type="button" onClick={() => onAdd()} className="figma-btn-primary"><Plus size={14} />Add Evidence</button></div> : shown.length === 0 ? <div className="px-5 py-16 text-center text-xs text-[#8b8f98]">No evidence in this category yet.</div> : shown.map((record) => <article key={record.id} role="button" tabIndex={0} onClick={() => onOpen(record.id)} onKeyDown={(event) => (event.key === "Enter" || event.key === " ") && onOpen(record.id)} className={`group relative rounded-[8px] border px-4 py-3.5 shadow-[0_1px_3px_rgba(16,24,40,.06)] transition hover:-translate-y-px hover:shadow-[0_4px_12px_rgba(16,24,40,.08)] focus-visible:z-10 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-[#2f5bea]/35 sm:px-5 ${record.status === "pending" ? "border-[#f2dfaa] bg-[#fffdf7]" : record.status === "approved" ? "border-[#c8ead8] bg-[#fbfffc]" : record.status === "rejected" ? "border-[#f0caca] bg-[#fffafa]" : "border-[#ded4f4] bg-[#fdfbff]"}`}><div className="flex items-start gap-3"><SkillIcon skill={record.skill} size={25}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-1.5"><h2 className="m-0 text-[11px] font-semibold text-[#17181d]">{record.skill}</h2><TypeBadge type={record.type}/></div><p className="m-0 mt-1 truncate text-[9px] leading-4 text-[#777b84]">{record.description}</p><a href={record.url} target="_blank" rel="noreferrer" onClick={(event) => event.stopPropagation()} className="mt-0.5 block truncate text-[9px] text-[#969aa2] hover:text-[#2f5bea] hover:underline">{record.url}</a>{record.reviewNote && <div className={`mt-2 rounded-[3px] border px-2 py-1.5 text-[9px] leading-4 ${record.status === "approved" ? "border-[#cdebdc] bg-[#f0fbf4] text-[#4d7c60]" : record.status === "rejected" ? "border-[#f4d1d1] bg-[#fff6f6] text-[#985050]" : "border-[#e3daf7] bg-[#faf8ff] text-[#7053a1]"}`}><span className="font-semibold">Reviewer note: </span>{truncate(record.reviewNote, 155)}</div>}</div><div className="flex shrink-0 flex-col items-end gap-1 text-right"><StatusBadge status={record.status} plain size="sm"/><p className="m-0 text-[8px] text-[#a1a4ac]">Submitted {fmt(record.submittedAt)}</p>{(record.status === "rejected" || record.status === "revision") && <button type="button" onClick={(event) => { event.stopPropagation(); onAdd(record.id); }} className="mt-0.5 inline-flex items-center gap-1 text-[9px] font-semibold text-[#2f5bea] hover:underline"><RotateCcw size={10}/>Resubmit Evidence</button>}</div></div></article>)}</div>
    </div>
  </main>;
}
